name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install jo
      run: sudo apt install jo -y

    - name: npm install
      run: npm install

    - name: Package
      run: npx pkg node_modules/svgo

    - name: Create JSON
      run: jo -p version=$(./svgo-linux -v) \
          mac_sha256=$(sha256sum ./svgo-macos | head -c 64) \
          mac_size=$(wc -c < ./svgo-macos | xargs) \
          linux_sha256=$(sha256sum ./svgo-linux | head -c 64) \
          linux_size=$(wc -c < ./svgo-linux | xargs) \
          windows_sha256=$(sha256sum svgo-win.exe | head -c 64) \
          windows_size=$(wc -c < ./svgo-win.exe | xargs)
      
    - uses: actions/upload-artifact@v1
      with:
        name: svgo-macos
        path: svgo-macos

    - uses: actions/upload-artifact@v1
      with:
        name: svgo-linux
        path: svgo-linux

    - uses: actions/upload-artifact@v1
      with:
        name: svgo-win.exe
        path: svgo-win.exe
